customerror/custom_error.go
request/request_tools.go

por error en librería de beego

Se comenta beego.Error()

---

request/request_tools.go

Se modifican funciones GetJson y SendJson para inyectar cabecera, en caso de que esta se tenga. Si no se cuenta con ella, se agrega excepcion (try-catch) para que las peticiones se realicen normalmente. Tambien, se agregan funciones Get y SetHeader para capturar cabecera. Se probaron nuevas funcionalidades en APIs de Titan, tanto cuando se cuenta con cabecera como cuando no y las funciones arrojan los mismos resultados que antes del ajuste

Modificaciones de librería para implementación de auditoría en mid_api

---

README.md
formatdata/json_tools.go
request/transaction_tools.go
requestmanager/requestmanager.go
responseformat/README.md
responseformat/response_format.go
resposeformat/response_format.go
ruler/ruler_tools.go
time_bogota/time_bogota.go

se crea y documentan funciones para la hora en Bogotá

Hora bogota

---

apiStatusLib/apistatus.go

feat: apiHealthCheck critical log on failure

---

auditoria/middleware.go

Tiene que ver con:
Después de la validación funciona ok.

devops: Monitoría y control de errores variable user_agent

---

xray/xray.go

feat: mejora XRAY

---

xray/xray.go

feat: Desarrollo de funcionalidades para control de estados en AWS-XRay

feat: Desarrollo de funcionalidades para control de estados en AWS-XRay

---

xray/xray.go

feat: implementación de nuevas funcionalidades en X-Ray y documentación de código.

feat: implementación de nuevas funcionalidades en X-Ray y documentación de código.

---

xray/xray.go

feat: actualización XRAY

---

request/request_tools.go
xray/xray.go

feat: Instrumentación de request con XRAY y desactivación de Logs

feat: Instrumentación de request con XRAY y desactivación de Logs

---

request/request_tools.go

feature: función para post sin encode unicode

Merge from feature/SendJsonEscapeUnicode to master

---

request/request_tools.go
request/transaction_tools.go
xray/xray.go

feat: actualización de utilidades y request y variable de entorno global

feat: actualización de utilidades y request y variable de entorno global

---

auditoriaPruebas/middleware.go

https://github.com/udistrital/core_documentacion/issues/285

Ajuste al serializar el json 

---

errorctrlPrueba/errorctrl.go

Esto corresponde al issue [Realizar prueba de implementación de errores en utils_oas](https://github.com/udistrital/core_documentacion/issues/292)

Se quitan imports innecesarios

---

auditoriaPruebas/middleware.go

https://github.com/udistrital/core_documentacion/issues/285

Ajuste al serializar el json prueba 2

---

auditoriaPruebas/middleware.go

https://github.com/udistrital/core_documentacion/issues/285

Ajuste al serializar el json tercera prueba

---

auditoriaPruebas/middleware.go

https://github.com/udistrital/core_documentacion/issues/285

Ajuste probado para serializar a json el middleware

---

auditoriaPruebas/middleware.go

https://github.com/udistrital/core_documentacion/issues/302

Desarrollo de captura del SQL generado por el ORM

---

errorctrlPrueba/errorctrl.go

Esto corresponde al issue [Sobre la reunión de presentación de errores a funcionamiento](https://github.com/udistrital/core_documentacion/issues/317)

Se quitan codigos de respuesta quemados

---

auditoria/interceptor.go
auditoria/middleware.go

Se modifica librería de auditoría para interceptar mensajes de error de las APIS. Esto corresponde al issue [Realizar prueba de implementación de errores en utils_oas](https://github.com/udistrital/core_documentacion/issues/292)

Se modifica librería de auditoría 

---

errorctrl/errorctrl.go

Esto corresponde al issue [Reunión de muestra a funciónamiento de manejo de errores](https://github.com/udistrital/core_documentacion/issues/317)

Se pasa código de prueba a errorctrl original
